# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.utilidades


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seguridad', '0004_auto_20170404_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=144)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cta_created_by', to='seguridad.Profile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cta_updated_by', to='seguridad.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCentroAtencion',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=144)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical centro atencion',
            },
        ),
        migrations.CreateModel(
            name='HistoricalIncidenciaDocumento',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=144)),
                ('registrable', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField()),
                ('empleado_id', models.IntegerField(default=0)),
                ('empleado_nombre', models.CharField(max_length=144)),
                ('empleado_zona', models.CharField(max_length=144)),
                ('empleado_proyecto', models.CharField(max_length=50)),
                ('empleado_proyecto_desc', models.CharField(max_length=144)),
                ('empleado_puesto', models.IntegerField(default=0)),
                ('empleado_puesto_desc', models.CharField(max_length=144)),
                ('empleado_un', models.CharField(max_length=144)),
                ('empleado_organizacion', models.CharField(max_length=144)),
                ('area_id', models.IntegerField(default=0)),
                ('area_descripcion', models.CharField(max_length=144)),
                ('lugar', models.CharField(max_length=144)),
                ('dias_incapcidad', models.IntegerField(default=0)),
                ('acr', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('abi', 'Abierto'), ('cer', 'Cerrado'), ('pro', 'Proceso'), ('can', 'Cancelado')], default='abi', max_length=3)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('centro_atencion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sgi.CentroAtencion')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical incidencia documento',
            },
        ),
        migrations.CreateModel(
            name='HistoricalIncidenciaResolucion',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical incidencia resolucion',
            },
        ),
        migrations.CreateModel(
            name='HistoricalIncidenciaTipos',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=144)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical incidencia tipos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalResolucionTipo',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=144)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical resolucion tipo',
            },
        ),
        migrations.CreateModel(
            name='IncidenciaArchivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alt', 'Alta'), ('mod', 'Modificacion'), ('seg', 'Seguimiento')], default='abi', max_length=3)),
                ('archivo', models.FileField(upload_to=home.utilidades.get_FilePath)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iar_created_by', to='seguridad.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=144)),
                ('registrable', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField()),
                ('empleado_id', models.IntegerField(default=0)),
                ('empleado_nombre', models.CharField(max_length=144)),
                ('empleado_zona', models.CharField(max_length=144)),
                ('empleado_proyecto', models.CharField(max_length=50)),
                ('empleado_proyecto_desc', models.CharField(max_length=144)),
                ('empleado_puesto', models.IntegerField(default=0)),
                ('empleado_puesto_desc', models.CharField(max_length=144)),
                ('empleado_un', models.CharField(max_length=144)),
                ('empleado_organizacion', models.CharField(max_length=144)),
                ('area_id', models.IntegerField(default=0)),
                ('area_descripcion', models.CharField(max_length=144)),
                ('lugar', models.CharField(max_length=144)),
                ('dias_incapcidad', models.IntegerField(default=0)),
                ('acr', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('abi', 'Abierto'), ('cer', 'Cerrado'), ('pro', 'Proceso'), ('can', 'Cancelado')], default='abi', max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('centro_atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgi.CentroAtencion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dci_created_by', to='seguridad.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaResolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ire_created_by', to='seguridad.Profile')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgi.IncidenciaDocumento')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaTipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=144)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpi_created_by', to='seguridad.Profile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpi_updated_by', to='seguridad.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ResolucionArchivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=home.utilidades.get_FilePath)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rar_created_by', to='seguridad.Profile')),
                ('resolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgi.IncidenciaResolucion')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rar_updated_by', to='seguridad.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ResolucionTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=144)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ret_created_by', to='seguridad.Profile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ret_updated_by', to='seguridad.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='incidenciaresolucion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgi.ResolucionTipo'),
        ),
        migrations.AddField(
            model_name='incidenciaresolucion',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ire_updated_by', to='seguridad.Profile'),
        ),
        migrations.AddField(
            model_name='incidenciadocumento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgi.IncidenciaTipos'),
        ),
        migrations.AddField(
            model_name='incidenciadocumento',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dci_updated_by', to='seguridad.Profile'),
        ),
        migrations.AddField(
            model_name='incidenciaarchivo',
            name='incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgi.IncidenciaDocumento'),
        ),
        migrations.AddField(
            model_name='incidenciaarchivo',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iar_updated_by', to='seguridad.Profile'),
        ),
        migrations.AddField(
            model_name='historicalincidenciaresolucion',
            name='incidencia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sgi.IncidenciaDocumento'),
        ),
        migrations.AddField(
            model_name='historicalincidenciaresolucion',
            name='tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sgi.ResolucionTipo'),
        ),
        migrations.AddField(
            model_name='historicalincidenciaresolucion',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile'),
        ),
        migrations.AddField(
            model_name='historicalincidenciadocumento',
            name='tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sgi.IncidenciaTipos'),
        ),
        migrations.AddField(
            model_name='historicalincidenciadocumento',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile'),
        ),
    ]
