# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 16:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seguridad', '0001_initial'),
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalViaticoCabecera',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('empleado_clave', models.IntegerField(default=0)),
                ('empleado_descripcion', models.CharField(max_length=60, null=True)),
                ('fecha_partida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('unidad_negocio_clave', models.CharField(max_length=80)),
                ('unidad_negocio_descripcion', models.CharField(max_length=144, null=True)),
                ('ciudad_destino', models.CharField(max_length=150)),
                ('proposito_viaje', models.TextField(max_length=250)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('grupo', models.CharField(blank=True, max_length=40, null=True)),
                ('autorizador_clave', models.IntegerField(blank=True, default=0)),
                ('autorizador_descripcion', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(choices=[('cap', 'En edici\xf3n'), ('sau', 'Sin autorizar'), ('aut', 'Autorizado'), ('rec', 'Rechazado'), ('fin', 'Finalizado'), ('can', 'Cancelado')], default='cap', max_length=3)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('importe_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administracion.Empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical viatico cabecera',
            },
        ),
        migrations.CreateModel(
            name='HistoricalViaticoLinea',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('concepto', models.CharField(max_length=60)),
                ('observaciones', models.CharField(max_length=140)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical viatico linea',
            },
        ),
        migrations.CreateModel(
            name='ViaticoCabecera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_clave', models.IntegerField(default=0)),
                ('empleado_descripcion', models.CharField(max_length=60, null=True)),
                ('fecha_partida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('unidad_negocio_clave', models.CharField(max_length=80)),
                ('unidad_negocio_descripcion', models.CharField(max_length=144, null=True)),
                ('ciudad_destino', models.CharField(max_length=150)),
                ('proposito_viaje', models.TextField(max_length=250)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('grupo', models.CharField(blank=True, max_length=40, null=True)),
                ('autorizador_clave', models.IntegerField(blank=True, default=0)),
                ('autorizador_descripcion', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(choices=[('cap', 'En edici\xf3n'), ('sau', 'Sin autorizar'), ('aut', 'Autorizado'), ('rec', 'Rechazado'), ('fin', 'Finalizado'), ('can', 'Cancelado')], default='cap', max_length=3)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('importe_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='via_autorizador', to='seguridad.Profile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='via_created_by', to='seguridad.Profile')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Empresa')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='via_updated_by', to='seguridad.Profile')),
            ],
            options={
                'verbose_name_plural': 'Viaticos Cabeceras',
            },
        ),
        migrations.CreateModel(
            name='ViaticoLinea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=60)),
                ('observaciones', models.CharField(max_length=140)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosempleado.ViaticoCabecera')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vialinea_created_by', to='seguridad.Profile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vialinea_updated_by', to='seguridad.Profile')),
            ],
            options={
                'verbose_name_plural': 'Viaticos Lineas',
            },
        ),
        migrations.AddField(
            model_name='historicalviaticolinea',
            name='cabecera',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='serviciosempleado.ViaticoCabecera'),
        ),
        migrations.AddField(
            model_name='historicalviaticolinea',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile'),
        ),
        migrations.AddField(
            model_name='historicalviaticolinea',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalviaticolinea',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile'),
        ),
    ]
