# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=60)),
                ('apellido_materno', models.CharField(max_length=60)),
                ('genero', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=60)),
                ('puesto', models.CharField(max_length=60)),
                ('organizacion', models.CharField(max_length=60)),
                ('fecha_inicio_contratacion', models.CharField(max_length=60)),
                ('fecha_fin_contratacion', models.CharField(max_length=60)),
                ('compania', models.CharField(max_length=60)),
                ('zona', models.CharField(max_length=60)),
                ('centro_costos', models.CharField(max_length=60)),
                ('nomina', models.CharField(max_length=60)),
            ],
        ),
    ]
