# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import seguridadlaboral.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seguridad', '0001_initial'),
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIEW_INCIDENCIAS_ZONA',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('trir', models.CharField(max_length=240)),
                ('total_incidencias', models.CharField(max_length=240)),
                ('descripcion', models.CharField(max_length=240)),
                ('anio', models.CharField(max_length=240)),
                ('totalempleado', models.CharField(max_length=240)),
            ],
            options={
                'db_table': 'VIEW_INCIDENCIAS_ZONA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CentroAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=144)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scta_created_by', to='seguridad.Profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scta_updated_by', to='seguridad.Profile')),
            ],
            options={
                'verbose_name_plural': 'Centros de Atencion',
            },
        ),
        migrations.CreateModel(
            name='EmpleadosZona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalempleado', models.IntegerField(default=0)),
                ('incidencias_registrables', models.IntegerField(default=0)),
                ('anio', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xsempzon_created_by', to='seguridad.Profile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xsempzon_updated_by', to='seguridad.Profile')),
                ('zona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.Zona')),
            ],
            options={
                'verbose_name_plural': 'Empleados por Zona',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCentroAtencion',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=144)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical centro atencion',
            },
        ),
        migrations.CreateModel(
            name='HistoricalIncidenciaResolucion',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('abi', 'Abierto'), ('cer', 'Cerrado'), ('pro', 'Proceso'), ('can', 'Cancelado')], default='abi', max_length=3)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical incidencia resolucion',
            },
        ),
        migrations.CreateModel(
            name='HistoricalIncidenciaTipo',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=144)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical incidencia tipo',
            },
        ),
        migrations.CreateModel(
            name='HistoricalResolucionTipo',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=144)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical resolucion tipo',
            },
        ),
        migrations.CreateModel(
            name='IncidenciaArchivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alt', 'Alta'), ('mod', 'Modificacion'), ('seg', 'Seguimiento')], default='abi', max_length=3)),
                ('archivo', models.FileField(upload_to=seguridadlaboral.utilities.get_FilePath_Incidencia)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siar_created_by', to='seguridad.Profile')),
            ],
            options={
                'verbose_name_plural': 'Archivos de Incidencia',
            },
        ),
        migrations.CreateModel(
            name='IncidenciaDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_registrable', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField()),
                ('empleado_id', models.IntegerField(default=0)),
                ('empleado_nombre', models.CharField(max_length=144)),
                ('empleado_proyecto', models.CharField(max_length=50)),
                ('empleado_proyecto_desc', models.CharField(max_length=144)),
                ('empleado_puesto', models.IntegerField(default=0)),
                ('empleado_puesto_desc', models.CharField(max_length=144)),
                ('empleado_un', models.CharField(max_length=144)),
                ('area_id', models.IntegerField(default=0)),
                ('area_descripcion', models.CharField(max_length=144)),
                ('lugar', models.CharField(max_length=144)),
                ('dias_incapcidad', models.IntegerField(blank=True, default=0)),
                ('tiene_acr', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('abi', 'Abierto'), ('cer', 'Cerrado'), ('pro', 'Proceso'), ('can', 'Cancelado')], default='abi', max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('centro_atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguridadlaboral.CentroAtencion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdci_created_by', to='seguridad.Profile')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.Empresa')),
            ],
            options={
                'verbose_name_plural': 'Documentos de Incidencia',
            },
        ),
        migrations.CreateModel(
            name='IncidenciaResolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('abi', 'Abierto'), ('cer', 'Cerrado'), ('pro', 'Proceso'), ('can', 'Cancelado')], default='abi', max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sire_created_by', to='seguridad.Profile')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridadlaboral.IncidenciaDocumento')),
            ],
            options={
                'verbose_name_plural': 'Resoluciones',
            },
        ),
        migrations.CreateModel(
            name='IncidenciaTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=144)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stpi_created_by', to='seguridad.Profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stpi_updated_by', to='seguridad.Profile')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Incidencia',
            },
        ),
        migrations.CreateModel(
            name='ResolucionArchivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=seguridadlaboral.utilities.get_FilePath_Resolucion)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srar_created_by', to='seguridad.Profile')),
                ('resolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridadlaboral.IncidenciaResolucion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='srar_updated_by', to='seguridad.Profile')),
            ],
            options={
                'verbose_name_plural': 'Archivos de resolucion',
            },
        ),
        migrations.CreateModel(
            name='ResolucionTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=144)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sret_created_by', to='seguridad.Profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sret_updated_by', to='seguridad.Profile')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Resolucion',
            },
        ),
        migrations.AddField(
            model_name='incidenciaresolucion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguridadlaboral.ResolucionTipo'),
        ),
        migrations.AddField(
            model_name='incidenciaresolucion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sire_updated_by', to='seguridad.Profile'),
        ),
        migrations.AddField(
            model_name='incidenciadocumento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguridadlaboral.IncidenciaTipo'),
        ),
        migrations.AddField(
            model_name='incidenciadocumento',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdci_updated_by', to='seguridad.Profile'),
        ),
        migrations.AddField(
            model_name='incidenciadocumento',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.Zona'),
        ),
        migrations.AddField(
            model_name='incidenciaarchivo',
            name='incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridadlaboral.IncidenciaDocumento'),
        ),
        migrations.AddField(
            model_name='incidenciaarchivo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siar_updated_by', to='seguridad.Profile'),
        ),
        migrations.AddField(
            model_name='historicalincidenciaresolucion',
            name='incidencia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridadlaboral.IncidenciaDocumento'),
        ),
        migrations.AddField(
            model_name='historicalincidenciaresolucion',
            name='tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridadlaboral.ResolucionTipo'),
        ),
        migrations.AddField(
            model_name='historicalincidenciaresolucion',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguridad.Profile'),
        ),
    ]
