# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='F0101',
            fields=[
                ('clave', models.IntegerField(db_column='ABAN8', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='ABALPH', max_length=40)),
                ('tipo', models.CharField(db_column='ABAT1', max_length=3)),
                ('rfc', models.CharField(db_column='ABTAX', max_length=20)),
            ],
            options={
                'db_table': '"CRPDTA"."F0101"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VIEW_UNIDADES',
            fields=[
                ('clave', models.CharField(db_column='CLAVE', max_length=12, primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='TIPO', max_length=2)),
                ('compania', models.CharField(db_column='COMPANIA', max_length=5)),
                ('desc_corta', models.CharField(db_column='DESC_CORTA', max_length=30)),
                ('desc_larga', models.CharField(db_column='DESC_LARGA', max_length=75)),
                ('reclass', models.CharField(db_column='RECLASS', max_length=10)),
            ],
            options={
                'db_table': '"NUVPD"."VIEW_UNIDADES"',
                'managed': False,
            },
        ),
    ]
